### ISSUE TITLE
Custom names for cropping definitions (and public link relativeURL)

### ISSUE THREAD

**Issue by jorgenjanssonlee** [robhabraken/content-hub-focal-point-cropping#14]
Hi Rob,

Can I raise a feature request for the ability to specify a custom name for each cropping definition? Or more specifically the ratio style crops, but it's probably easier (and might be useful) to implement it for fixed pixel styles as well.

The reason is that some UX designers prefer to work with named ratios like web-banner, hero, portrait instead of 16x9, 4x3 etc. It would make the communication between UX and front-end developers easier if both sides are using the same terms and the public link is actually named with the same term that UX is using.

Just to clarify, the underlying cropping based on ratio values doesn't need changing, what I'm asking for is the ability to give it a custom or "alias" name that is used by the public link relativeURL

I'm not a developer, but it looks like this could be done by adding ah "custom name" parameter to the CroppingDefintion in the script "DAM - Create public links for cropping". And obviously use this when calculating the name and creating the relativeUrl.

Something like this maybe? For the original rendition I think it's fine to keep the current hardcoded "original" name

`// configure auto-generated croppings`
`var croppings = new Dictionary<string, CroppingDefinition>();`
`AddCroppingDefinition(0, 0, 0, 0, true);
`AddCroppingDefinition(0, 0, 16, 9, "landscape");`
`AddCroppingDefinition(0, 0, 4, 3, "tile");`
`AddCroppingDefinition(0, 0, 1, 1, "square");`

**Comment by robhabraken** [comment]
Hi Jorgen,

What a great idea! Our team uses the ratios in front-end code to dynamically configure or request the desired cropping, so they wanted numbers, but I can totally see why you would want to use names for this. Although it is equally complex to build in this functionality for both pixel dimensions as for ratios, it felt more appropriate to only do it for ratios first, as I kind of see the dimensions as the non-preferred route for backwards compatibility (as it was my first version), and I do want to steer towards using ratios only.

Consider it done :-). But be aware, there is somewhat of a breaking change in the cropping configuration! The original boolean moved to the first parameter (because I cannot have two unrelated conditional parameters) and also flipped! So what used to be "true" to get the original, is now "false" indicating if you want to crop. The name became the new optional value on the end of the parameter list. This all felt more logical when you are looking at or explaining the parameter list. I also updated the accompanying readme file.

Looking forward to hear your feedback on this and I hope you can quickly implement this desired change.

NB: I do have a different version for one of our customers, that uses the asset ID instead of the asset title, so that the public link will be named more consistently (more robust, since the ID does never change). If you want are interested in that please let me know.

Regards, Rob
